image: docker-registry.linagora.com:5000/linshare-snapshots/linshare-build-helper:latest
stages:
  - build

check_author:
  image: docker-registry.linagora.com:5000/lgs-releases/gitlab-integrity-checks:latest
  stage: build
  variables:
    GIT_DEPTH: "1"
  tags:
    - ultralight
  script:
    - check_author.py check "$GITLAB_USER_EMAIL" "$GITLAB_USER_NAME" --no-accents
  except:
    refs:
      - master@linagora/lgs/linshare/products/linshare-ui-upload-request
      - tags@linagora/lgs/linshare/products/linshare-ui-upload-request
      - /^release-.*/@linagora/lgs/linshare/products/linshare-ui-upload-request

build:
  stage: build
  tags:
    - docker
  script:
    - mvn clean test
